# Generated by kuma. Edit kuma.toml instead.
FROM localhost/kuma-base:m4f2229bac93b

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 cosmic-session cosmic-edit flatpak fastfetch gnome-keyring gnome-keyring-pam pipewire pipewire-pulseaudio wireplumber mesa-dri-drivers mesa-vulkan-drivers vulkan-loader glibc-langpack-en NetworkManager-wifi wpa_supplicant power-profiles-daemon bluez firewalld zram-generator-defaults avahi nss-mdns cups system-config-printer spice-vdagent udisks2 default-fonts-core-emoji google-noto-sans-cjk-vf-fonts adwaita-icon-theme desktop-file-utils
RUN --mount=type=cache,target=/var/cache/libdnf5 \
    rm -rf /var/cache/libdnf5/@commandline-* \
    && dnf -y install --setopt=keepcache=1 "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
    && v_mesa=$(rpm -q --qf '%{version}' mesa-libEGL) \
    && v_free=$(dnf -q repoquery --latest-limit=1 --qf '%{version}' mesa-va-drivers-freeworld) \
    && { if [ -z "$v_free" ]; then \
        echo "repoquery found no mesa-va-drivers-freeworld candidate - cannot tell whether the freeworld build lags Fedora's mesa; failing rather than composing blind" >&2; \
        exit 1; \
    elif [ "$v_free" = "$v_mesa" ]; then \
        dnf -y install --setopt=keepcache=1 --allowerasing mesa-va-drivers-freeworld; \
    else \
        echo "note: mesa-freeworld's build ($v_free) lags Fedora's mesa ($v_mesa) - installing it would downgrade mesa to the build whose LLVM JIT crashes the greeter (kumaOS#36)" >&2; \
        echo "skipping the freeworld install: VA-API decode falls back to CPU until rpmfusion's rebuild catches up" >&2; \
    fi; }
RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 --allowerasing ffmpeg-libs
RUN rm /etc/xdg/autostart/com.system76.CosmicInitialSetup.desktop
RUN printf 'COSMIC_DISABLE_OVERLAY_SCANOUT=1\nCOSMIC_DISABLE_DIRECT_SCANOUT=1\n' >> /etc/environment
RUN test -f /usr/lib64/security/pam_gnome_keyring.so \
    && grep -q pam_gnome_keyring /etc/pam.d/cosmic-greeter /usr/lib/pam.d/cosmic-greeter 2>/dev/null
COPY kargs-desktop.toml /usr/lib/bootc/kargs.d/10-kuma-desktop.toml
COPY fastfetch-config.jsonc /etc/xdg/fastfetch/config.jsonc
COPY fastfetch-logo.txt /usr/lib/kuma/fastfetch-logo.txt
COPY kuma-wallpaper.jpg /usr/share/backgrounds/kuma/kuma-wallpaper.jpg
RUN test -f /usr/share/cosmic/com.system76.CosmicAppList/v1/favorites \
    && test -f /usr/share/cosmic/com.system76.CosmicBackground/v1/all
COPY cosmic-favorites /usr/share/cosmic/com.system76.CosmicAppList/v1/favorites
COPY cosmic-background /usr/share/cosmic/com.system76.CosmicBackground/v1/all
RUN systemctl set-default graphical.target && systemctl enable cosmic-greeter.service firewalld.service power-profiles-daemon.service bluetooth.service cups.service avahi-daemon.service chronyd.service
RUN curl --fail -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo \
    && systemctl mask flatpak-add-fedora-repos.service
COPY flatpaks /usr/lib/kuma/flatpaks
COPY --chmod=755 kuma-flatpak-sync /usr/libexec/kuma-flatpak-sync
COPY kuma-flatpak-sync.service /usr/lib/systemd/system/kuma-flatpak-sync.service
COPY kuma-flatpak-sync.timer /usr/lib/systemd/system/kuma-flatpak-sync.timer
COPY --chmod=755 kuma-converge-gate /usr/libexec/kuma-converge-gate
COPY kuma-flatpak-sync-daily.service /usr/lib/systemd/system/kuma-flatpak-sync-daily.service
RUN systemctl enable kuma-flatpak-sync.service kuma-flatpak-sync.timer
COPY overrides /usr/lib/kuma/overrides
COPY kuma-flatpak-overrides.service /usr/lib/systemd/system/kuma-flatpak-overrides.service
COPY kuma-flatpak-overrides-user.service /usr/lib/systemd/user/kuma-flatpak-overrides.service
RUN systemctl enable kuma-flatpak-overrides.service \
    && systemctl --global enable kuma-flatpak-overrides.service

RUN systemctl enable sshd.service

COPY hardening-sysctl.conf /usr/lib/sysctl.d/70-kuma-hardening.conf
COPY kargs-hardening.toml /usr/lib/bootc/kargs.d/05-kuma-hardening.toml
COPY public.zone.xml /etc/firewalld/zones/public.xml
COPY chrony.conf /etc/chrony.conf
COPY kuma-mac.conf /etc/NetworkManager/conf.d/kuma-mac.conf
COPY faillock.conf /etc/security/faillock.conf

RUN authselect enable-feature with-faillock && authselect apply-changes

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 fuse fuse-libs

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 greenboot

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 plymouth plymouth-plugin-script plymouth-plugin-label dejavu-sans-fonts
COPY plymouth /usr/share/plymouth/themes/spinner_alt/
RUN printf '%s\n' '[Daemon]' 'Theme=spinner_alt' > /etc/plymouth/plymouthd.conf \
    && ln -sfn spinner_alt/spinner_alt.plymouth /usr/share/plymouth/themes/default.plymouth
RUN printf '%s\n' 'add_dracutmodules+=" plymouth "' > /etc/dracut.conf.d/kuma-plymouth.conf
RUN set -eux; \
    kver="$(ls /usr/lib/modules)"; \
    test "$(echo "$kver" | wc -l)" -eq 1; \
    mkdir -p /var/roothome; \
    dconf="$(mktemp -d)"; \
    printf '%s\n' 'sysloglvl=0' > "$dconf/99-kuma-build.conf"; \
    dracut --add-confdir "$dconf" --force --no-hostonly --add plymouth "/usr/lib/modules/$kver/initramfs.img" "$kver"
COPY --chmod=755 kuma-greeter-check /usr/lib/greenboot/check/required.d/50-kuma-greeter.sh
COPY --chmod=755 kuma-launch /usr/libexec/kuma-launch
COPY kuma-edit.desktop /usr/share/applications/kuma-edit.desktop
COPY kuma-drift.desktop /usr/share/applications/kuma-drift.desktop
COPY kuma-proposals.desktop /usr/share/applications/kuma-proposals.desktop
COPY kuma-doctor.desktop /usr/share/applications/kuma-doctor.desktop
COPY kuma-update.desktop /usr/share/applications/kuma-update.desktop
COPY kuma-build.desktop /usr/share/applications/kuma-build.desktop
COPY kuma-rollback.desktop /usr/share/applications/kuma-rollback.desktop
COPY kuma-snapshots.desktop /usr/share/applications/kuma-snapshots.desktop
RUN desktop-file-validate /usr/share/applications/kuma-edit.desktop /usr/share/applications/kuma-drift.desktop /usr/share/applications/kuma-proposals.desktop /usr/share/applications/kuma-doctor.desktop /usr/share/applications/kuma-update.desktop /usr/share/applications/kuma-build.desktop /usr/share/applications/kuma-rollback.desktop /usr/share/applications/kuma-snapshots.desktop
RUN test -x /usr/libexec/kuma-launch \
    && find /usr/share/icons/Adwaita -name text-editor-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name edit-find-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name dialog-information-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name emblem-system-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name software-update-available-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name view-refresh-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name go-previous-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name drive-harddisk-symbolic.svg | grep -q .
COPY --chmod=755 kuma-boot-health-sync /usr/libexec/kuma-boot-health-sync
COPY kuma-boot-health-sync.service /usr/lib/systemd/system/kuma-boot-health-sync.service
COPY kuma-swap-fcontext /etc/selinux/targeted/contexts/files/file_contexts.local
COPY kuma-swap-label.service /usr/lib/systemd/system/kuma-swap-label.service
COPY --chmod=755 kuma-fstab-sync /usr/libexec/kuma-fstab-sync
COPY kuma-fstab-sync.service /usr/lib/systemd/system/kuma-fstab-sync.service
COPY kuma-boot-titles.service /usr/lib/systemd/system/kuma-boot-titles.service
RUN systemctl enable greenboot-healthcheck.service greenboot-set-rollback-trigger.service greenboot-success.target kuma-boot-health-sync.service kuma-fstab-sync.service kuma-boot-titles.service kuma-swap-label.service

COPY cosign.pub /etc/pki/containers/kuma.pub
COPY containers-policy.json /etc/containers/policy.json
COPY kuma-sigstore.yaml /etc/containers/registries.d/kuma-sigstore.yaml
RUN systemctl enable fwupd-refresh.timer

COPY --chmod=755 kuma-vm-timezone /usr/libexec/kuma-vm-timezone
COPY kuma-vm-timezone.service /usr/lib/systemd/system/kuma-vm-timezone.service
RUN systemctl enable kuma-vm-timezone.service

COPY --chmod=755 kuma-home-subvol /usr/libexec/kuma-home-subvol
COPY kuma-home-subvol.service /usr/lib/systemd/system/kuma-home-subvol.service
RUN systemctl enable kuma-home-subvol.service

COPY --chmod=755 kuma-user-sync /usr/libexec/kuma-user-sync
COPY kuma-user-sync.service /usr/lib/systemd/system/kuma-user-sync.service
RUN systemctl enable kuma-user-sync.service

COPY hostname /etc/hostname

RUN . /usr/lib/os-release \
    && case "${VERSION_ID}" in \
        44) CODENAME="Beorn" ;; \
        45) CODENAME="Callisto" ;; \
        46) CODENAME="Ephraim" ;; \
        47) CODENAME="Grizzly" ;; \
        48) CODENAME="Helarctos" ;; \
        49) CODENAME="Iorek" ;; \
        50) CODENAME="Jambavan" ;; \
        51) CODENAME="Kodiak" ;; \
        *) CODENAME="" ;; \
    esac \
    && sed -i \
        -e 's|^NAME=.*|NAME="kumaOS"|' \
        -e "s|^PRETTY_NAME=.*|PRETTY_NAME=\"kumaOS 44.7.0${CODENAME:+ ($CODENAME)}\"|" \
        -e "s|^VERSION=.*|VERSION=\"44.7.0${CODENAME:+ ($CODENAME)}\"|" \
        -e 's|^ID=.*|ID=kuma|' \
        -e 's|^DEFAULT_HOSTNAME=.*|DEFAULT_HOSTNAME="kumaos"|' \
        -e 's|^ANSI_COLOR=.*|ANSI_COLOR="0;38;2;126;224;168"|' \
        /usr/lib/os-release \
    && if [ -n "$CODENAME" ]; then sed -i \
        -e "s|^VERSION_CODENAME=.*|VERSION_CODENAME=$(printf %s "$CODENAME" | tr '[:upper:]' '[:lower:]')|" \
        /usr/lib/os-release; fi \
    && { grep -q '^ID_LIKE=' /usr/lib/os-release || echo 'ID_LIKE="fedora"' >> /usr/lib/os-release; } \
    && { [ ! -f /usr/lib/fedora-release ] || echo "kumaOS release ${VERSION_ID}${CODENAME:+ ($CODENAME)}" > /usr/lib/fedora-release; }

COPY --chmod=755 kuma /usr/bin/kuma
RUN /usr/bin/kuma --version

COPY kuma.toml /usr/lib/kuma/kuma.toml

LABEL io.kuma.image="1"
LABEL io.kuma.builder=<version-and-commit>
LABEL org.opencontainers.image.version="44.7.0"

RUN find /run /tmp -mindepth 1 -delete; \
    find /var/log -type f -delete; \
    ! find /var/log -type f | grep -q .

RUN said=$(bootc container lint 2>&1); rc=$?; \
    printf '%s\n' "$said"; \
    if [ $rc -ne 0 ] && printf '%s' "$said" | grep -q 'var-tmpfiles: I/O error'; then \
        rc=0; bootc container lint --skip var-tmpfiles || rc=$?; \
    fi; \
    exit $rc
