# Generated by kuma. Edit kuma.toml instead.
FROM localhost/kuma-base:m5b1f3da61dcf

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 --exclude=alacritty --exclude=waybar --exclude=swaylock --exclude=fuzzel flatpak niri xwayland-satellite greetd tuigreet kitty pipewire pipewire-pulseaudio wireplumber xdg-desktop-portal-gtk xdg-desktop-portal-gnome dconf gnome-keyring gnome-keyring-pam polkit mesa-dri-drivers mesa-vulkan-drivers vulkan-loader default-fonts-core-sans default-fonts-core-mono fontawesome-fonts-all glibc-langpack-en NetworkManager-wifi adwaita-icon-theme adw-gtk3-theme desktop-file-utils NetworkManager-tui wpa_supplicant brightnessctl power-profiles-daemon pavucontrol nm-connection-editor bluez blueman file-roller gvfs gvfs-mtp gvfs-fuse gvfs-smb wf-recorder zram-generator-defaults avahi nss-mdns libnotify cups system-config-printer wl-clipboard xsettingsd spice-vdagent xdg-user-dirs default-fonts-core-emoji mate-polkit firewalld grim slurp swappy playerctl udiskie 7zip unar google-noto-sans-cjk-vf-fonts fastfetch
RUN --mount=type=cache,target=/var/cache/libdnf5 \
    rm -rf /var/cache/libdnf5/@commandline-* \
    && dnf -y install --setopt=keepcache=1 "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
    && dnf -y install --setopt=keepcache=1 --allowerasing mesa-va-drivers-freeworld
RUN test -d /usr/share/themes/adw-gtk3-dark
COPY greetd-config.toml /etc/greetd/config.toml
COPY greetd-restart.conf /usr/lib/systemd/system/greetd.service.d/10-kuma-restart.conf
COPY kuma-greeter-tmpfiles.conf /usr/lib/tmpfiles.d/kuma-greeter.conf
COPY greeter-niri.kdl /usr/share/kumaos/greeter-niri.kdl
RUN niri validate --config /usr/share/kumaos/greeter-niri.kdl
COPY --chmod=755 kuma-greeter-session /usr/libexec/kuma-greeter-session
COPY kargs-desktop.toml /usr/lib/bootc/kargs.d/10-kuma-desktop.toml
COPY niri-extras.kdl /usr/lib/kuma/niri-extras.kdl
COPY kuma-wallpaper.jpg /usr/share/backgrounds/kuma/kuma-wallpaper.jpg
COPY --chmod=755 kuma-shell /usr/bin/kuma-shell
COPY --chmod=755 kuma-greeter /usr/bin/kuma-greeter
COPY --chmod=755 kuma-files /usr/bin/kuma-files
COPY kuma-files.desktop /usr/share/applications/kuma-files.desktop
COPY kuma-files.png /usr/share/icons/hicolor/256x256/apps/kuma-files.png
RUN desktop-file-validate /usr/share/applications/kuma-files.desktop \
    && test -x /usr/bin/kuma-files \
    && test -f /usr/share/icons/hicolor/256x256/apps/kuma-files.png
COPY kitty.conf /etc/xdg/kitty/kitty.conf
RUN rc=0; kitty +runpy "import sys; from kitty.config import load_config; bad = []; load_config('/etc/xdg/kitty/kitty.conf', accumulate_bad_lines=bad); sys.exit('malformed kitty.conf lines: %s' % bad if bad else 0)" 2>/tmp/kitty.err || rc=$?; \
    cat /tmp/kitty.err >&2; \
    if grep -q 'unknown config key' /tmp/kitty.err; then rc=1; fi; \
    rm -f /tmp/kitty.err; exit $rc
COPY --chmod=755 kuma-clipboard-bridge /usr/libexec/kuma-clipboard-bridge
COPY fastfetch-config.jsonc /etc/xdg/fastfetch/config.jsonc
COPY fastfetch-logo.txt /usr/lib/kuma/fastfetch-logo.txt
COPY --chmod=755 kuma-xsettings /usr/libexec/kuma-xsettings
COPY xsettingsd.conf /usr/lib/kuma/xsettingsd.conf
COPY niri-binds.kdl /usr/lib/kuma/niri-binds.kdl
COPY --chmod=755 kuma-record /usr/libexec/kuma-record
COPY --chmod=755 kuma-battery-watch /usr/libexec/kuma-battery-watch
COPY kuma-shell.service /usr/lib/systemd/user/kuma-shell.service
COPY kuma-sleep-guard.service /usr/lib/systemd/system/kuma-sleep-guard.service
COPY --chmod=755 kuma-sleep-guard /usr/libexec/kuma-sleep-guard
RUN systemctl --global enable kuma-shell.service \
    && systemctl enable kuma-sleep-guard.service
COPY gtk3-settings.ini /etc/gtk-3.0/settings.ini
COPY gtk4-settings.ini /etc/gtk-4.0/settings.ini
COPY mimeapps.list /etc/xdg/mimeapps.list
COPY dconf-profile /etc/dconf/profile/user
RUN test -f /usr/lib64/security/pam_gnome_keyring.so \
    && grep -q pam_gnome_keyring /etc/pam.d/greetd /usr/lib/pam.d/greetd 2>/dev/null
COPY kuma-lock /etc/pam.d/kuma-lock
COPY dconf-kuma-dark /etc/dconf/db/local.d/10-kuma-dark
COPY dconf-kuma-blueman /etc/dconf/db/local.d/10-kuma-blueman
RUN dconf update
COPY autostart-blueman /etc/xdg/autostart/blueman.desktop
COPY autostart-polkit-mate /etc/xdg/autostart/polkit-mate-authentication-agent-1.desktop
RUN grep -q '"alacritty"' /usr/share/doc/niri/default-config.kdl \
    && grep -qF 'Mod+D hotkey-overlay-title="Run an Application: fuzzel" { spawn "fuzzel"; }' /usr/share/doc/niri/default-config.kdl \
    && grep -qF 'Super+Alt+L hotkey-overlay-title="Lock the Screen: swaylock" { spawn "swaylock"; }' /usr/share/doc/niri/default-config.kdl \
    && grep -qF 'Super+Alt+S allow-when-locked=true hotkey-overlay-title=null { spawn-sh "pkill orca || exec orca"; }' /usr/share/doc/niri/default-config.kdl \
    && grep -qF '// skip-at-startup' /usr/share/doc/niri/default-config.kdl \
    && grep -q '^layout {' /usr/share/doc/niri/default-config.kdl \
    && mkdir -p /etc/niri \
    && sed -e 's/alacritty/kitty/g' -e '/starts waybar/d' -e '/^spawn-at-startup "waybar"$/d' -e '/XF86Audio/d' -e '/XF86MonBrightness/d' -e 's|// skip-at-startup|skip-at-startup|' -e '/^layout {/a\    background-color "#11111B"' -e 's|Mod+D hotkey-overlay-title="Run an Application: fuzzel" { spawn "fuzzel"; }|Mod+D hotkey-overlay-title="Toggle Applications menu" { spawn "kuma-shell" "msg" "launcher-toggle"; }|' -e 's|Super+Alt+L hotkey-overlay-title="Lock the Screen: swaylock" { spawn "swaylock"; }|Super+Alt+L hotkey-overlay-title="Lock the Screen" { spawn "loginctl" "lock-session"; }|' -e '/pkill orca/d' -e '/^binds {/r /usr/lib/kuma/niri-binds.kdl' /usr/share/doc/niri/default-config.kdl > /etc/niri/config.kdl \
    && cat /usr/lib/kuma/niri-extras.kdl >> /etc/niri/config.kdl \
    && niri validate --config /etc/niri/config.kdl
RUN grep -q '^\[preferred\]' /usr/share/xdg-desktop-portal/niri-portals.conf \
    && grep -q 'org.freedesktop.impl.portal.FileChooser' /usr/share/xdg-desktop-portal/portals/gtk.portal \
    && mkdir -p /etc/xdg-desktop-portal \
    && { cat /usr/share/xdg-desktop-portal/niri-portals.conf; echo 'org.freedesktop.impl.portal.FileChooser=gtk;'; } > /etc/xdg-desktop-portal/niri-portals.conf
RUN grep -qx '    systemctl --user import-environment' /usr/bin/niri-session \
    && sed -i 's/^    systemctl --user import-environment$/    systemctl --user import-environment PATH XDG_SESSION_ID XDG_SEAT XDG_VTNR/' /usr/bin/niri-session
RUN systemctl set-default graphical.target && systemctl enable greetd.service firewalld.service power-profiles-daemon.service bluetooth.service cups.service avahi-daemon.service chronyd.service
RUN curl --fail -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo \
    && systemctl mask flatpak-add-fedora-repos.service
COPY flatpaks /usr/lib/kuma/flatpaks
COPY --chmod=755 kuma-flatpak-sync /usr/libexec/kuma-flatpak-sync
COPY kuma-flatpak-sync.service /usr/lib/systemd/system/kuma-flatpak-sync.service
COPY kuma-flatpak-sync.timer /usr/lib/systemd/system/kuma-flatpak-sync.timer
COPY --chmod=755 kuma-converge-gate /usr/libexec/kuma-converge-gate
COPY kuma-flatpak-sync-daily.service /usr/lib/systemd/system/kuma-flatpak-sync-daily.service
RUN systemctl enable kuma-flatpak-sync.service kuma-flatpak-sync.timer
COPY overrides /usr/lib/kuma/overrides
COPY kuma-flatpak-overrides.service /usr/lib/systemd/system/kuma-flatpak-overrides.service
COPY kuma-flatpak-overrides-user.service /usr/lib/systemd/user/kuma-flatpak-overrides.service
RUN systemctl enable kuma-flatpak-overrides.service \
    && systemctl --global enable kuma-flatpak-overrides.service

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 git-core tar
COPY --chmod=755 kuma-brew-setup /usr/libexec/kuma-brew-setup
COPY kuma-brew-setup.service /usr/lib/systemd/system/kuma-brew-setup.service
COPY brew-profile.sh /etc/profile.d/kuma-brew.sh
COPY brew-profile.fish /etc/fish/conf.d/kuma-brew.fish
COPY brews /usr/lib/kuma/brews
COPY --chmod=755 kuma-brew-sync /usr/libexec/kuma-brew-sync
COPY kuma-brew-sync.service /usr/lib/systemd/system/kuma-brew-sync.service
COPY kuma-brew-sync.timer /usr/lib/systemd/system/kuma-brew-sync.timer
COPY --chmod=755 kuma-converge-gate /usr/libexec/kuma-converge-gate
COPY kuma-brew-sync-daily.service /usr/lib/systemd/system/kuma-brew-sync-daily.service
RUN systemctl enable kuma-brew-setup.service kuma-brew-sync.service kuma-brew-sync.timer

RUN systemctl enable sshd.service

RUN systemctl enable sshd.service && systemctl enable tailscaled.service

COPY hardening-sysctl.conf /usr/lib/sysctl.d/70-kuma-hardening.conf
COPY kargs-hardening.toml /usr/lib/bootc/kargs.d/05-kuma-hardening.toml
COPY public.zone.xml /etc/firewalld/zones/public.xml
COPY chrony.conf /etc/chrony.conf
COPY kuma-mac.conf /etc/NetworkManager/conf.d/kuma-mac.conf
COPY faillock.conf /etc/security/faillock.conf

RUN authselect enable-feature with-faillock && authselect apply-changes

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 fuse fuse-libs

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 greenboot

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 plymouth plymouth-plugin-script plymouth-plugin-label dejavu-sans-fonts
COPY plymouth /usr/share/plymouth/themes/spinner_alt/
RUN printf '%s\n' '[Daemon]' 'Theme=spinner_alt' > /etc/plymouth/plymouthd.conf \
    && ln -sfn spinner_alt/spinner_alt.plymouth /usr/share/plymouth/themes/default.plymouth
RUN printf '%s\n' 'add_dracutmodules+=" plymouth "' > /etc/dracut.conf.d/kuma-plymouth.conf
RUN set -eux; \
    kver="$(ls /usr/lib/modules)"; \
    test "$(echo "$kver" | wc -l)" -eq 1; \
    mkdir -p /var/roothome; \
    dconf="$(mktemp -d)"; \
    printf '%s\n' 'sysloglvl=0' > "$dconf/99-kuma-build.conf"; \
    dracut --add-confdir "$dconf" --force --no-hostonly --add plymouth "/usr/lib/modules/$kver/initramfs.img" "$kver"
COPY --chmod=755 kuma-greeter-check /usr/lib/greenboot/check/required.d/50-kuma-greeter.sh
COPY --chmod=755 kuma-launch /usr/libexec/kuma-launch
COPY kuma-edit.desktop /usr/share/applications/kuma-edit.desktop
COPY kuma-drift.desktop /usr/share/applications/kuma-drift.desktop
COPY kuma-proposals.desktop /usr/share/applications/kuma-proposals.desktop
COPY kuma-doctor.desktop /usr/share/applications/kuma-doctor.desktop
COPY kuma-update.desktop /usr/share/applications/kuma-update.desktop
COPY kuma-build.desktop /usr/share/applications/kuma-build.desktop
COPY kuma-rollback.desktop /usr/share/applications/kuma-rollback.desktop
COPY kuma-snapshots.desktop /usr/share/applications/kuma-snapshots.desktop
RUN desktop-file-validate /usr/share/applications/kuma-edit.desktop /usr/share/applications/kuma-drift.desktop /usr/share/applications/kuma-proposals.desktop /usr/share/applications/kuma-doctor.desktop /usr/share/applications/kuma-update.desktop /usr/share/applications/kuma-build.desktop /usr/share/applications/kuma-rollback.desktop /usr/share/applications/kuma-snapshots.desktop
RUN test -x /usr/libexec/kuma-launch \
    && find /usr/share/icons/Adwaita -name text-editor-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name edit-find-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name dialog-information-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name emblem-system-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name software-update-available-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name view-refresh-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name go-previous-symbolic.svg | grep -q . \
    && find /usr/share/icons/Adwaita -name drive-harddisk-symbolic.svg | grep -q .
COPY --chmod=755 kuma-boot-health-sync /usr/libexec/kuma-boot-health-sync
COPY kuma-boot-health-sync.service /usr/lib/systemd/system/kuma-boot-health-sync.service
COPY kuma-swap-fcontext /etc/selinux/targeted/contexts/files/file_contexts.local
COPY kuma-swap-label.service /usr/lib/systemd/system/kuma-swap-label.service
COPY --chmod=755 kuma-fstab-sync /usr/libexec/kuma-fstab-sync
COPY kuma-fstab-sync.service /usr/lib/systemd/system/kuma-fstab-sync.service
COPY kuma-boot-titles.service /usr/lib/systemd/system/kuma-boot-titles.service
RUN systemctl enable greenboot-healthcheck.service greenboot-set-rollback-trigger.service greenboot-success.target kuma-boot-health-sync.service kuma-fstab-sync.service kuma-boot-titles.service kuma-swap-label.service

COPY cosign.pub /etc/pki/containers/kuma.pub
COPY containers-policy.json /etc/containers/policy.json
COPY kuma-sigstore.yaml /etc/containers/registries.d/kuma-sigstore.yaml
RUN systemctl enable fwupd-refresh.timer

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 btrfs-progs
COPY --chmod=755 kuma-snapshot /usr/libexec/kuma-snapshot
COPY kuma-snapshot.service /usr/lib/systemd/system/kuma-snapshot.service
COPY kuma-snapshot.timer /usr/lib/systemd/system/kuma-snapshot.timer
RUN systemctl enable kuma-snapshot.timer

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 restic
COPY --chmod=755 kuma-backup /usr/libexec/kuma-backup
COPY kuma-backup.service /usr/lib/systemd/system/kuma-backup.service
COPY kuma-backup.timer /usr/lib/systemd/system/kuma-backup.timer
RUN systemctl enable kuma-backup.timer
COPY --chmod=755 kuma-restore /usr/libexec/kuma-restore
COPY kuma-restore.service /usr/lib/systemd/system/kuma-restore.service
RUN systemctl enable kuma-restore.service

COPY --chmod=755 kuma-nostrd /usr/bin/kuma-nostrd
COPY --chmod=755 kuma-nostr /usr/bin/kuma-nostr
COPY kuma-nostrd.service /usr/lib/systemd/user/kuma-nostrd.service
COPY --chmod=755 nip46-relay /usr/bin/nip46-relay
COPY nip46-relay.service /usr/lib/systemd/user/nip46-relay.service
COPY --chmod=755 kuma-nostr-serve /usr/libexec/kuma-nostr-serve
COPY kuma-nostr-serve.service /usr/lib/systemd/system/kuma-nostr-serve.service
RUN systemctl enable kuma-nostr-serve.service
RUN systemctl --global enable kuma-nostrd.service nip46-relay.service
RUN /usr/bin/kuma-nostrd --version
COPY kuma-nostr-panel.desktop /usr/share/applications/kuma-nostr-panel.desktop

COPY --chmod=755 kuma-vm-timezone /usr/libexec/kuma-vm-timezone
COPY kuma-vm-timezone.service /usr/lib/systemd/system/kuma-vm-timezone.service
RUN systemctl enable kuma-vm-timezone.service

RUN test -e /usr/share/zoneinfo/Pacific/Auckland && ln -sfn /usr/share/zoneinfo/Pacific/Auckland /etc/localtime

COPY --chmod=755 kuma-home-subvol /usr/libexec/kuma-home-subvol
COPY kuma-home-subvol.service /usr/lib/systemd/system/kuma-home-subvol.service
RUN systemctl enable kuma-home-subvol.service

COPY --chmod=755 kuma-user-sync /usr/libexec/kuma-user-sync
COPY kuma-user-sync.service /usr/lib/systemd/system/kuma-user-sync.service
RUN systemctl enable kuma-user-sync.service
COPY --chmod=600 kuma-user /usr/lib/kuma/user
COPY kuma-user-keys /etc/kuma/keys/probe
COPY kuma-sshd-keys.conf /etc/ssh/sshd_config.d/40-kuma-keys.conf

COPY hostname /etc/hostname

RUN . /usr/lib/os-release \
    && case "${VERSION_ID}" in \
        44) CODENAME="Beorn" ;; \
        45) CODENAME="Callisto" ;; \
        46) CODENAME="Ephraim" ;; \
        47) CODENAME="Grizzly" ;; \
        48) CODENAME="Helarctos" ;; \
        49) CODENAME="Iorek" ;; \
        50) CODENAME="Jambavan" ;; \
        51) CODENAME="Kodiak" ;; \
        *) CODENAME="" ;; \
    esac \
    && sed -i \
        -e 's|^NAME=.*|NAME="kumaOS"|' \
        -e "s|^PRETTY_NAME=.*|PRETTY_NAME=\"kumaOS 44.6.0${CODENAME:+ ($CODENAME)}\"|" \
        -e "s|^VERSION=.*|VERSION=\"44.6.0${CODENAME:+ ($CODENAME)}\"|" \
        -e 's|^ID=.*|ID=kuma|' \
        -e 's|^DEFAULT_HOSTNAME=.*|DEFAULT_HOSTNAME="kumaos"|' \
        -e 's|^ANSI_COLOR=.*|ANSI_COLOR="0;38;2;126;224;168"|' \
        /usr/lib/os-release \
    && if [ -n "$CODENAME" ]; then sed -i \
        -e "s|^VERSION_CODENAME=.*|VERSION_CODENAME=$(printf %s "$CODENAME" | tr '[:upper:]' '[:lower:]')|" \
        /usr/lib/os-release; fi \
    && { grep -q '^ID_LIKE=' /usr/lib/os-release || echo 'ID_LIKE="fedora"' >> /usr/lib/os-release; } \
    && { [ ! -f /usr/lib/fedora-release ] || echo "kumaOS release ${VERSION_ID}${CODENAME:+ ($CODENAME)}" > /usr/lib/fedora-release; }

COPY --chmod=755 kuma /usr/bin/kuma
RUN /usr/bin/kuma --version

COPY kuma.toml /usr/lib/kuma/kuma.toml

LABEL io.kuma.image="1"
LABEL io.kuma.builder=<version-and-commit>
LABEL org.opencontainers.image.version="44.6.0"

RUN find /run /tmp -mindepth 1 -delete; \
    find /var/log -type f -delete; \
    ! find /var/log -type f | grep -q .

RUN said=$(bootc container lint 2>&1); rc=$?; \
    printf '%s\n' "$said"; \
    if [ $rc -ne 0 ] && printf '%s' "$said" | grep -q 'var-tmpfiles: I/O error'; then \
        rc=0; bootc container lint --skip var-tmpfiles || rc=$?; \
    fi; \
    exit $rc
