# Generated by kuma. Edit kuma.toml instead.
FROM localhost/kuma-base:m5b1f3da61dcf

RUN systemctl enable sshd.service

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 fuse fuse-libs

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 greenboot

RUN --mount=type=cache,target=/var/cache/libdnf5 \
    dnf -y install --setopt=keepcache=1 plymouth plymouth-plugin-script plymouth-plugin-label dejavu-sans-fonts
COPY plymouth /usr/share/plymouth/themes/spinner_alt/
RUN printf '%s\n' '[Daemon]' 'Theme=spinner_alt' > /etc/plymouth/plymouthd.conf \
    && ln -sfn spinner_alt/spinner_alt.plymouth /usr/share/plymouth/themes/default.plymouth
RUN printf '%s\n' 'add_dracutmodules+=" plymouth "' > /etc/dracut.conf.d/kuma-plymouth.conf
RUN set -eux; \
    kver="$(ls /usr/lib/modules)"; \
    test "$(echo "$kver" | wc -l)" -eq 1; \
    mkdir -p /var/roothome; \
    dconf="$(mktemp -d)"; \
    printf '%s\n' 'sysloglvl=0' > "$dconf/99-kuma-build.conf"; \
    dracut --add-confdir "$dconf" --force --no-hostonly --add plymouth "/usr/lib/modules/$kver/initramfs.img" "$kver"
COPY --chmod=755 kuma-boot-health-sync /usr/libexec/kuma-boot-health-sync
COPY kuma-boot-health-sync.service /usr/lib/systemd/system/kuma-boot-health-sync.service
COPY kuma-swap-fcontext /etc/selinux/targeted/contexts/files/file_contexts.local
COPY kuma-swap-label.service /usr/lib/systemd/system/kuma-swap-label.service
COPY --chmod=755 kuma-fstab-sync /usr/libexec/kuma-fstab-sync
COPY kuma-fstab-sync.service /usr/lib/systemd/system/kuma-fstab-sync.service
COPY kuma-boot-titles.service /usr/lib/systemd/system/kuma-boot-titles.service
RUN systemctl enable greenboot-healthcheck.service greenboot-set-rollback-trigger.service greenboot-success.target kuma-boot-health-sync.service kuma-fstab-sync.service kuma-boot-titles.service kuma-swap-label.service

COPY cosign.pub /etc/pki/containers/kuma.pub
COPY containers-policy.json /etc/containers/policy.json
COPY kuma-sigstore.yaml /etc/containers/registries.d/kuma-sigstore.yaml
RUN systemctl enable fwupd-refresh.timer

COPY --chmod=755 kuma-vm-timezone /usr/libexec/kuma-vm-timezone
COPY kuma-vm-timezone.service /usr/lib/systemd/system/kuma-vm-timezone.service
RUN systemctl enable kuma-vm-timezone.service

COPY --chmod=755 kuma-home-subvol /usr/libexec/kuma-home-subvol
COPY kuma-home-subvol.service /usr/lib/systemd/system/kuma-home-subvol.service
RUN systemctl enable kuma-home-subvol.service

COPY --chmod=755 kuma-user-sync /usr/libexec/kuma-user-sync
COPY kuma-user-sync.service /usr/lib/systemd/system/kuma-user-sync.service
RUN systemctl enable kuma-user-sync.service

COPY hostname /etc/hostname

RUN . /usr/lib/os-release \
    && case "${VERSION_ID}" in \
        44) CODENAME="Beorn" ;; \
        45) CODENAME="Callisto" ;; \
        46) CODENAME="Ephraim" ;; \
        47) CODENAME="Grizzly" ;; \
        48) CODENAME="Helarctos" ;; \
        49) CODENAME="Iorek" ;; \
        50) CODENAME="Jambavan" ;; \
        51) CODENAME="Kodiak" ;; \
        *) CODENAME="" ;; \
    esac \
    && sed -i \
        -e 's|^NAME=.*|NAME="kumaOS"|' \
        -e "s|^PRETTY_NAME=.*|PRETTY_NAME=\"kumaOS 44.5.0${CODENAME:+ ($CODENAME)}\"|" \
        -e "s|^VERSION=.*|VERSION=\"44.5.0${CODENAME:+ ($CODENAME)}\"|" \
        -e 's|^ID=.*|ID=kuma|' \
        -e 's|^DEFAULT_HOSTNAME=.*|DEFAULT_HOSTNAME="kumaos"|' \
        -e 's|^ANSI_COLOR=.*|ANSI_COLOR="0;38;2;126;224;168"|' \
        /usr/lib/os-release \
    && if [ -n "$CODENAME" ]; then sed -i \
        -e "s|^VERSION_CODENAME=.*|VERSION_CODENAME=$(printf %s "$CODENAME" | tr '[:upper:]' '[:lower:]')|" \
        /usr/lib/os-release; fi \
    && { grep -q '^ID_LIKE=' /usr/lib/os-release || echo 'ID_LIKE="fedora"' >> /usr/lib/os-release; } \
    && { [ ! -f /usr/lib/fedora-release ] || echo "kumaOS release ${VERSION_ID}${CODENAME:+ ($CODENAME)}" > /usr/lib/fedora-release; }

COPY --chmod=755 kuma /usr/bin/kuma
RUN /usr/bin/kuma --version

COPY kuma.toml /usr/lib/kuma/kuma.toml

LABEL io.kuma.image="1"
LABEL io.kuma.builder=<version-and-commit>
LABEL org.opencontainers.image.version="44.5.0"

RUN find /run /tmp -mindepth 1 -delete; \
    find /var/log -type f -delete; \
    ! find /var/log -type f | grep -q .

RUN said=$(bootc container lint 2>&1); rc=$?; \
    printf '%s\n' "$said"; \
    if [ $rc -ne 0 ] && printf '%s' "$said" | grep -q 'var-tmpfiles: I/O error'; then \
        rc=0; bootc container lint --skip var-tmpfiles || rc=$?; \
    fi; \
    exit $rc
